version: '3.8'

services:
  nginx:
    image: nginx:1.24
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
  api:
    image: dauid64/tutoria1.0
    env_file:
      - ./docker_env/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
      - ./docker_env/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./docker_env/.env
    ports:
      - "15432:80"